// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: protos/player_actions.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerAction int32

const (
	PlayerAction_REROLL PlayerAction = 0
	PlayerAction_BID    PlayerAction = 1
	PlayerAction_CALL   PlayerAction = 2
	PlayerAction_STAY   PlayerAction = 3
)

// Enum value maps for PlayerAction.
var (
	PlayerAction_name = map[int32]string{
		0: "REROLL",
		1: "BID",
		2: "CALL",
		3: "STAY",
	}
	PlayerAction_value = map[string]int32{
		"REROLL": 0,
		"BID":    1,
		"CALL":   2,
		"STAY":   3,
	}
)

func (x PlayerAction) Enum() *PlayerAction {
	p := new(PlayerAction)
	*p = x
	return p
}

func (x PlayerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_player_actions_proto_enumTypes[0].Descriptor()
}

func (PlayerAction) Type() protoreflect.EnumType {
	return &file_protos_player_actions_proto_enumTypes[0]
}

func (x PlayerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerAction.Descriptor instead.
func (PlayerAction) EnumDescriptor() ([]byte, []int) {
	return file_protos_player_actions_proto_rawDescGZIP(), []int{0}
}

type ValidBid int32

const (
	ValidBid_SINGLE          ValidBid = 0
	ValidBid_ONE_PAIR        ValidBid = 1
	ValidBid_TWO_PAIR        ValidBid = 2
	ValidBid_THREE_OF_A_KIND ValidBid = 3
	ValidBid_LOW_STRAIGHT    ValidBid = 4
	ValidBid_HIGH_STRAIGHT   ValidBid = 5
	ValidBid_FULL_HOUSE      ValidBid = 6
	ValidBid_FOUR_OF_A_KIND  ValidBid = 7
	ValidBid_FIVE_OF_A_KIND  ValidBid = 8
)

// Enum value maps for ValidBid.
var (
	ValidBid_name = map[int32]string{
		0: "SINGLE",
		1: "ONE_PAIR",
		2: "TWO_PAIR",
		3: "THREE_OF_A_KIND",
		4: "LOW_STRAIGHT",
		5: "HIGH_STRAIGHT",
		6: "FULL_HOUSE",
		7: "FOUR_OF_A_KIND",
		8: "FIVE_OF_A_KIND",
	}
	ValidBid_value = map[string]int32{
		"SINGLE":          0,
		"ONE_PAIR":        1,
		"TWO_PAIR":        2,
		"THREE_OF_A_KIND": 3,
		"LOW_STRAIGHT":    4,
		"HIGH_STRAIGHT":   5,
		"FULL_HOUSE":      6,
		"FOUR_OF_A_KIND":  7,
		"FIVE_OF_A_KIND":  8,
	}
)

func (x ValidBid) Enum() *ValidBid {
	p := new(ValidBid)
	*p = x
	return p
}

func (x ValidBid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidBid) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_player_actions_proto_enumTypes[1].Descriptor()
}

func (ValidBid) Type() protoreflect.EnumType {
	return &file_protos_player_actions_proto_enumTypes[1]
}

func (x ValidBid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidBid.Descriptor instead.
func (ValidBid) EnumDescriptor() ([]byte, []int) {
	return file_protos_player_actions_proto_rawDescGZIP(), []int{1}
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string       `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action   PlayerAction `protobuf:"varint,2,opt,name=action,proto3,enum=PlayerAction" json:"action,omitempty"`
	// Types that are assignable to Data:
	//
	//	*Action_Reroll
	//	*Action_Bid
	//	*Action_Call
	//	*Action_Stay
	Data isAction_Data `protobuf_oneof:"data"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_player_actions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_protos_player_actions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_protos_player_actions_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Action) GetAction() PlayerAction {
	if x != nil {
		return x.Action
	}
	return PlayerAction_REROLL
}

func (m *Action) GetData() isAction_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Action) GetReroll() *RerollData {
	if x, ok := x.GetData().(*Action_Reroll); ok {
		return x.Reroll
	}
	return nil
}

func (x *Action) GetBid() *BidData {
	if x, ok := x.GetData().(*Action_Bid); ok {
		return x.Bid
	}
	return nil
}

func (x *Action) GetCall() *Empty {
	if x, ok := x.GetData().(*Action_Call); ok {
		return x.Call
	}
	return nil
}

func (x *Action) GetStay() *Empty {
	if x, ok := x.GetData().(*Action_Stay); ok {
		return x.Stay
	}
	return nil
}

type isAction_Data interface {
	isAction_Data()
}

type Action_Reroll struct {
	Reroll *RerollData `protobuf:"bytes,3,opt,name=reroll,proto3,oneof"`
}

type Action_Bid struct {
	Bid *BidData `protobuf:"bytes,4,opt,name=bid,proto3,oneof"`
}

type Action_Call struct {
	Call *Empty `protobuf:"bytes,5,opt,name=call,proto3,oneof"`
}

type Action_Stay struct {
	Stay *Empty `protobuf:"bytes,6,opt,name=stay,proto3,oneof"`
}

func (*Action_Reroll) isAction_Data() {}

func (*Action_Bid) isAction_Data() {}

func (*Action_Call) isAction_Data() {}

func (*Action_Stay) isAction_Data() {}

type RerollData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offsets []int32 `protobuf:"varint,1,rep,packed,name=offsets,proto3" json:"offsets,omitempty"`
}

func (x *RerollData) Reset() {
	*x = RerollData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_player_actions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RerollData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerollData) ProtoMessage() {}

func (x *RerollData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_player_actions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerollData.ProtoReflect.Descriptor instead.
func (*RerollData) Descriptor() ([]byte, []int) {
	return file_protos_player_actions_proto_rawDescGZIP(), []int{1}
}

func (x *RerollData) GetOffsets() []int32 {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type BidData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid   ValidBid `protobuf:"varint,1,opt,name=bid,proto3,enum=ValidBid" json:"bid,omitempty"`
	Wager int32    `protobuf:"varint,2,opt,name=wager,proto3" json:"wager,omitempty"`
}

func (x *BidData) Reset() {
	*x = BidData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_player_actions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidData) ProtoMessage() {}

func (x *BidData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_player_actions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidData.ProtoReflect.Descriptor instead.
func (*BidData) Descriptor() ([]byte, []int) {
	return file_protos_player_actions_proto_rawDescGZIP(), []int{2}
}

func (x *BidData) GetBid() ValidBid {
	if x != nil {
		return x.Bid
	}
	return ValidBid_SINGLE
}

func (x *BidData) GetWager() int32 {
	if x != nil {
		return x.Wager
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_player_actions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_player_actions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_player_actions_proto_rawDescGZIP(), []int{3}
}

var File_protos_player_actions_proto protoreflect.FileDescriptor

var file_protos_player_actions_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x06,
	0x72, 0x65, 0x72, 0x6f, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x52,
	0x65, 0x72, 0x6f, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x72,
	0x6f, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x42, 0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x03, 0x62, 0x69,
	0x64, 0x12, 0x1c, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x12,
	0x1c, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x61, 0x79, 0x42, 0x06, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x0a, 0x52, 0x65, 0x72, 0x6f, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x22, 0x3c, 0x0a,
	0x07, 0x42, 0x69, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x69, 0x64,
	0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x61, 0x67, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x61, 0x67, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x2a, 0x37, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x52, 0x4f, 0x4c, 0x4c, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x41, 0x4c,
	0x4c, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x54, 0x41, 0x59, 0x10, 0x03, 0x2a, 0xa4, 0x01,
	0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x69, 0x64, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x49,
	0x4e, 0x47, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x4e, 0x45, 0x5f, 0x50, 0x41,
	0x49, 0x52, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x57, 0x4f, 0x5f, 0x50, 0x41, 0x49, 0x52,
	0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x48, 0x52, 0x45, 0x45, 0x5f, 0x4f, 0x46, 0x5f, 0x41,
	0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x4f, 0x57, 0x5f, 0x53,
	0x54, 0x52, 0x41, 0x49, 0x47, 0x48, 0x54, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x49, 0x47,
	0x48, 0x5f, 0x53, 0x54, 0x52, 0x41, 0x49, 0x47, 0x48, 0x54, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a,
	0x46, 0x55, 0x4c, 0x4c, 0x5f, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e,
	0x46, 0x4f, 0x55, 0x52, 0x5f, 0x4f, 0x46, 0x5f, 0x41, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x10, 0x07,
	0x12, 0x12, 0x0a, 0x0e, 0x46, 0x49, 0x56, 0x45, 0x5f, 0x4f, 0x46, 0x5f, 0x41, 0x5f, 0x4b, 0x49,
	0x4e, 0x44, 0x10, 0x08, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_player_actions_proto_rawDescOnce sync.Once
	file_protos_player_actions_proto_rawDescData = file_protos_player_actions_proto_rawDesc
)

func file_protos_player_actions_proto_rawDescGZIP() []byte {
	file_protos_player_actions_proto_rawDescOnce.Do(func() {
		file_protos_player_actions_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_player_actions_proto_rawDescData)
	})
	return file_protos_player_actions_proto_rawDescData
}

var file_protos_player_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_player_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_player_actions_proto_goTypes = []interface{}{
	(PlayerAction)(0),  // 0: PlayerAction
	(ValidBid)(0),      // 1: ValidBid
	(*Action)(nil),     // 2: Action
	(*RerollData)(nil), // 3: RerollData
	(*BidData)(nil),    // 4: BidData
	(*Empty)(nil),      // 5: Empty
}
var file_protos_player_actions_proto_depIdxs = []int32{
	0, // 0: Action.action:type_name -> PlayerAction
	3, // 1: Action.reroll:type_name -> RerollData
	4, // 2: Action.bid:type_name -> BidData
	5, // 3: Action.call:type_name -> Empty
	5, // 4: Action.stay:type_name -> Empty
	1, // 5: BidData.bid:type_name -> ValidBid
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_player_actions_proto_init() }
func file_protos_player_actions_proto_init() {
	if File_protos_player_actions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_player_actions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_player_actions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RerollData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_player_actions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_player_actions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_player_actions_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Action_Reroll)(nil),
		(*Action_Bid)(nil),
		(*Action_Call)(nil),
		(*Action_Stay)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_player_actions_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_player_actions_proto_goTypes,
		DependencyIndexes: file_protos_player_actions_proto_depIdxs,
		EnumInfos:         file_protos_player_actions_proto_enumTypes,
		MessageInfos:      file_protos_player_actions_proto_msgTypes,
	}.Build()
	File_protos_player_actions_proto = out.File
	file_protos_player_actions_proto_rawDesc = nil
	file_protos_player_actions_proto_goTypes = nil
	file_protos_player_actions_proto_depIdxs = nil
}
