// @generated by protobuf-ts 2.11.0
// @generated from protobuf file "frontend_messages.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message CounterProps
 */
export interface CounterProps {
    /**
     * @generated from protobuf field: int32 startCount = 1
     */
    startCount: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class CounterProps$Type extends MessageType<CounterProps> {
    constructor() {
        super("CounterProps", [
            { no: 1, name: "startCount", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CounterProps>): CounterProps {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.startCount = 0;
        if (value !== undefined)
            reflectionMergePartial<CounterProps>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CounterProps): CounterProps {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 startCount */ 1:
                    message.startCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CounterProps, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 startCount = 1; */
        if (message.startCount !== 0)
            writer.tag(1, WireType.Varint).int32(message.startCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message CounterProps
 */
export const CounterProps = new CounterProps$Type();
